name: docker-build
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build
        run: |
          chmod +x build.sh
          ./build.sh
