name: docker-build
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: build
        run: |
          chmod +x build.sh
          ./build.sh
      - name: cache-tagname
        uses: actions/cache@v2
        with:
          path: "DUPLICATED_FILE"
          key: cache-dup-${{ hashFiles('TAGNAME') }}
      - name: duplicated-file
        run: |
          if [ -f "DUPLICATED_FILE" ]; then echo "DUPLICATED_FILE exists"; exit 0; fi
          touch DUPLICATED_FILE
